// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

  module sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2(a, b, c, d, p);
input [8 - 1 : 0] a; 
input [8 - 1 : 0] b; 
input [11 - 1 : 0] c; 
input [24 - 1 : 0] d; 
output [25 - 1 : 0] p; 

wire [9 - 1 : 0] s; 
assign s =  $unsigned (a) + $unsigned (b);
assign p =  $unsigned (s) * $unsigned (c) + $unsigned (d); 

endmodule

`timescale 1 ns / 1 ps
module sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1(
    din0,
    din1,
    din2,
    din3,
    dout);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter din2_WIDTH = 32'd1;
parameter din3_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input[din0_WIDTH - 1:0] din0;
input[din1_WIDTH - 1:0] din1;
input[din2_WIDTH - 1:0] din2;
input[din3_WIDTH - 1:0] din3;
output[dout_WIDTH - 1:0] dout;



sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2 sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2_U(
    .a( din0 ),
    .b( din1 ),
    .c( din2 ),
    .d( din3 ),
    .p( dout ));

endmodule

