// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

  module sobel_mac_muladd_8ns_11ns_21ns_21_1_DSP48_1(a, b, c, p);
input [8 - 1 : 0] a; 
input [11 - 1 : 0] b; 
input [21 - 1 : 0] c; 
output [21 - 1 : 0] p; 

assign p =  a * b + c;
endmodule

`timescale 1 ns / 1 ps
module sobel_mac_muladd_8ns_11ns_21ns_21_1(
    din0,
    din1,
    din2,
    dout);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter din2_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input[din0_WIDTH - 1:0] din0;
input[din1_WIDTH - 1:0] din1;
input[din2_WIDTH - 1:0] din2;
output[dout_WIDTH - 1:0] dout;



sobel_mac_muladd_8ns_11ns_21ns_21_1_DSP48_1 sobel_mac_muladd_8ns_11ns_21ns_21_1_DSP48_1_U(
    .a( din0 ),
    .b( din1 ),
    .c( din2 ),
    .p( dout ));

endmodule

