// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

(* use_dsp48 = "yes" *) module sobel_mac_muladd_8ns_8s_16s_16_1_DSP48_3(a, b, c, p);
input [8 - 1 : 0] a; 
input signed [8 - 1 : 0] b; 
input signed [16 - 1 : 0] c; 
output signed [16 - 1 : 0] p; 

assign p =  $signed ({1'b0,a}) * $signed (b) + $signed (c); 
endmodule

`timescale 1 ns / 1 ps
module sobel_mac_muladd_8ns_8s_16s_16_1(
    din0,
    din1,
    din2,
    dout);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter din2_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input[din0_WIDTH - 1:0] din0;
input[din1_WIDTH - 1:0] din1;
input[din2_WIDTH - 1:0] din2;
output[dout_WIDTH - 1:0] dout;



sobel_mac_muladd_8ns_8s_16s_16_1_DSP48_3 sobel_mac_muladd_8ns_8s_16s_16_1_DSP48_3_U(
    .a( din0 ),
    .b( din1 ),
    .c( din2 ),
    .p( dout ));

endmodule

