:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2015.2
:: Copyright (C) 2015 Xilinx Inc. All rights reserved.
:: 
:: ==============================================================


@echo off

C:/DISK/F/Xilinx/Vivado_HLS/2015.2/../../Vivado/2015.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z010clg400-1 ../xilinx_com_hls_sobel_1_0.zip
