-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.2
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ==============================================================


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2 is
port (
    a: in std_logic_vector(8 - 1 downto 0);
    b: in std_logic_vector(8 - 1 downto 0);
    c: in std_logic_vector(11 - 1 downto 0);
    d: in std_logic_vector(24 - 1 downto 0);
    p: out std_logic_vector(25 - 1 downto 0));

end entity;

architecture behav of sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2 is
    signal a_cvt: unsigned(9 - 1 downto 0);
    signal b_cvt: unsigned(9 - 1 downto 0);
    signal c_cvt: unsigned(11 - 1 downto 0);
    signal d_cvt: unsigned(24 - 1 downto 0);
    signal p_cvt: unsigned(25 - 1 downto 0);

begin

    a_cvt <= resize(unsigned(a), 9);
    b_cvt <= resize(unsigned(b), 9);
    c_cvt <= unsigned(c);
    d_cvt <= resize(unsigned(d), 24);
    p_cvt <= resize((unsigned ( (unsigned ( a_cvt) + unsigned (b_cvt))) * unsigned (c_cvt) + unsigned (d_cvt)), 25);
    p <= std_logic_vector(p_cvt);

end architecture;

Library IEEE;
use IEEE.std_logic_1164.all;

entity sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1 is
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER);
    port (
        din0 : IN STD_LOGIC_VECTOR(din0_WIDTH - 1 DOWNTO 0);
        din1 : IN STD_LOGIC_VECTOR(din1_WIDTH - 1 DOWNTO 0);
        din2 : IN STD_LOGIC_VECTOR(din2_WIDTH - 1 DOWNTO 0);
        din3 : IN STD_LOGIC_VECTOR(din3_WIDTH - 1 DOWNTO 0);
        dout : OUT STD_LOGIC_VECTOR(dout_WIDTH - 1 DOWNTO 0));
end entity;

architecture arch of sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1 is
    component sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2 is
        port (
            a : IN STD_LOGIC_VECTOR;
            b : IN STD_LOGIC_VECTOR;
            c : IN STD_LOGIC_VECTOR;
            d : IN STD_LOGIC_VECTOR;
            p : OUT STD_LOGIC_VECTOR);
    end component;



begin
    sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2_U :  component sobel_ama_addmuladd_8ns_8ns_11ns_24ns_25_1_DSP48_2
    port map (
        a => din0,
        b => din1,
        c => din2,
        d => din3,
        p => dout);

end architecture;


