// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsobel.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSobel_CfgInitialize(XSobel *InstancePtr, XSobel_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSobel_Start(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSobel_IsDone(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSobel_IsIdle(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSobel_IsReady(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSobel_EnableAutoRestart(XSobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSobel_DisableAutoRestart(XSobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XSobel_Set_rows(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XSobel_Get_rows(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XSobel_Set_cols(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XSobel_Get_cols(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XSobel_Set_C_XR0C0(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR0C0_DATA, Data);
}

u32 XSobel_Get_C_XR0C0(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR0C0_DATA);
    return Data;
}

void XSobel_Set_C_XR0C1(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR0C1_DATA, Data);
}

u32 XSobel_Get_C_XR0C1(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR0C1_DATA);
    return Data;
}

void XSobel_Set_C_XR0C2(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR0C2_DATA, Data);
}

u32 XSobel_Get_C_XR0C2(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR0C2_DATA);
    return Data;
}

void XSobel_Set_C_XR1C0(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR1C0_DATA, Data);
}

u32 XSobel_Get_C_XR1C0(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR1C0_DATA);
    return Data;
}

void XSobel_Set_C_XR1C1(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR1C1_DATA, Data);
}

u32 XSobel_Get_C_XR1C1(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR1C1_DATA);
    return Data;
}

void XSobel_Set_C_XR1C2(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR1C2_DATA, Data);
}

u32 XSobel_Get_C_XR1C2(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR1C2_DATA);
    return Data;
}

void XSobel_Set_C_XR2C0(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR2C0_DATA, Data);
}

u32 XSobel_Get_C_XR2C0(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR2C0_DATA);
    return Data;
}

void XSobel_Set_C_XR2C1(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR2C1_DATA, Data);
}

u32 XSobel_Get_C_XR2C1(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR2C1_DATA);
    return Data;
}

void XSobel_Set_C_XR2C2(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR2C2_DATA, Data);
}

u32 XSobel_Get_C_XR2C2(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_XR2C2_DATA);
    return Data;
}

void XSobel_Set_C_YR0C0(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR0C0_DATA, Data);
}

u32 XSobel_Get_C_YR0C0(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR0C0_DATA);
    return Data;
}

void XSobel_Set_C_YR0C1(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR0C1_DATA, Data);
}

u32 XSobel_Get_C_YR0C1(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR0C1_DATA);
    return Data;
}

void XSobel_Set_C_YR0C2(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR0C2_DATA, Data);
}

u32 XSobel_Get_C_YR0C2(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR0C2_DATA);
    return Data;
}

void XSobel_Set_C_YR1C0(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR1C0_DATA, Data);
}

u32 XSobel_Get_C_YR1C0(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR1C0_DATA);
    return Data;
}

void XSobel_Set_C_YR1C1(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR1C1_DATA, Data);
}

u32 XSobel_Get_C_YR1C1(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR1C1_DATA);
    return Data;
}

void XSobel_Set_C_YR1C2(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR1C2_DATA, Data);
}

u32 XSobel_Get_C_YR1C2(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR1C2_DATA);
    return Data;
}

void XSobel_Set_C_YR2C0(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR2C0_DATA, Data);
}

u32 XSobel_Get_C_YR2C0(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR2C0_DATA);
    return Data;
}

void XSobel_Set_C_YR2C1(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR2C1_DATA, Data);
}

u32 XSobel_Get_C_YR2C1(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR2C1_DATA);
    return Data;
}

void XSobel_Set_C_YR2C2(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR2C2_DATA, Data);
}

u32 XSobel_Get_C_YR2C2(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_YR2C2_DATA);
    return Data;
}

void XSobel_Set_c_high_thresh(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_HIGH_THRESH_DATA, Data);
}

u32 XSobel_Get_c_high_thresh(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_HIGH_THRESH_DATA);
    return Data;
}

void XSobel_Set_c_low_thresh(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA, Data);
}

u32 XSobel_Get_c_low_thresh(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA);
    return Data;
}

void XSobel_Set_c_invert(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_INVERT_DATA, Data);
}

u32 XSobel_Get_c_invert(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_C_INVERT_DATA);
    return Data;
}

void XSobel_Set_threshold(XSobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_THRESHOLD_DATA, Data);
}

u32 XSobel_Get_threshold(XSobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_THRESHOLD_DATA);
    return Data;
}

void XSobel_InterruptGlobalEnable(XSobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_GIE, 1);
}

void XSobel_InterruptGlobalDisable(XSobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_GIE, 0);
}

void XSobel_InterruptEnable(XSobel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_IER);
    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XSobel_InterruptDisable(XSobel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_IER);
    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XSobel_InterruptClear(XSobel *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_WriteReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XSobel_InterruptGetEnabled(XSobel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_IER);
}

u32 XSobel_InterruptGetStatus(XSobel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSobel_ReadReg(InstancePtr->Control_bus_BaseAddress, XSOBEL_CONTROL_BUS_ADDR_ISR);
}

